### ISSUE TITLE
Настройка CI

### ISSUE THREAD

**Issue by pavetok** [the-tale/the-tale#1750]
Настроил для своего форка план на [travis](https://travis-ci.org/pavetok/the-tale) и на [codeship](https://codeship.com/projects/103457/builds/8448453).
Проблема в том, что свалившиеся тесты не "валят" сборку:

```
FAIL: test_no_previouse_place (the_tale.game.actions.tests.test_action_inplace.InPlaceActionCompanionDrinkArtifactTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/pavetok/the-tale/the_tale/game/actions/tests/test_action_inplace.py", line 872, in test_no_previouse_place
    self.check_not_used()
  File "/home/travis/build/pavetok/the-tale/the_tale/game/actions/tests/test_action_inplace.py", line 867, in check_not_used
    prototypes.ActionInPlacePrototype.create(hero=self.hero)
  File "/opt/python/2.7.9/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/opt/python/2.7.9/lib/python2.7/contextlib.py", line 121, in nested
    if exit(*exc):
  File "/opt/python/2.7.9/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/travis/virtualenv/python2.7.9/src/dext/dext/common/utils/testcase.py", line 115, in check_not_changed
    self.assertEqual(callback(), old_value)
AssertionError: 6 != 5
----------------------------------------------------------------------
Ran 4259 tests in 1744.402s
FAILED (failures=1)
Destroying test database for alias 'default'...
test result:  1
The command "./manage.py dext_run_tests" exited with 0.
Done. Your build exited with 0.
```

Попутно несколько вопросов:
1. Нужно ли это для основного репозитория?
2. Если да, то нужно определиться с сервисом. Их конфигурация отличается принципиально. Но можно пока и оба использовать.

**Comment by Tiendil** [comment]
Поскольку в игре куча рандома, то иногда падают даже корректные тесты. Избавиться от этого достаточно сложно, поэтому не думаю, что тесты должны валить сборку.

Иметь CI само по себе не плохо, но особой надобности в ней сейчас для проекта нет. Для моей работы она не нужна, но была бы полезна для других разработчиков. Чтобы они могли легко подключить её к своим форкам. Если такой вариант можно сделать и добавить в вики инфу по нему, то пользу такая фича могла бы принести.

**Comment by pavetok** [comment]
Если в игре практически нет "посторонних" разработчиков, то особой надобности может и нет.
Хотя даже если был бы один разработчик, то ci-агент после каждого комита сам бы делал статический анализ, анализ покрытия, запускал тесты и присылал отчет. Что, на мой взгляд, сильно экономит время и силы. Не говоря уже о том, что все это будет запускаться по каждому пулл реквесту от сторонних разработчиков.

Если тесты не стабильные, то нормальной CI не получится :(
Придется анализировать результат каждой успешной сборки, чтобы найти тесты завалившиеся по твоей вине.

Даже безотносительно к CI нестабильные тесты приводят к издержкам (особенно у новых разработчиков), т.к. не понятно это твои изменения поломали тесты или нет.
Может есть смысл с этим как-то бороться?

С точки зрения полезности для других разработчиков travis лучше подходит, т.к. его вообще не нужно будет настраивать. Просто форкаешь репозиторий, авторизуешься в travis через github аккаунт и по следующему комиту запустится сборка. Единственный минус - travis более медленный.

**Comment by Tiendil** [comment]
С нестабильными тестами боремся, проблема в том, что они редко нестабильны. Если тест вдруг внезапно падает, я его чиню. 

Тогда на трависе можно и остановиться, скорость, я думаю, не большая проблема.

**Comment by pavetok** [comment]
Привет. В какую ветку делать пул реквест?

**Comment by Tiendil** [comment]
Подожди до завтра, создам новую ветку rc.0.3.21

**Comment by Tiendil** [comment]
Должна была быть закрыта давно.
