### ISSUE TITLE
Проекты: доработка механик

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2069]
Возможно, имеет смысл не делить ближний круг на два куска (соратники, противники).

Обсуждение: http://the-tale.org/forum/threads/1539?page=108#m185882

**Comment by ArgoTheTale** [comment]
Прошу в рамках этой задачи также пересмотреть понятие влияния от толпы, а точнее убрать его совсем. С вводом этого разделения в игру, стало очень сложно контролировать влияние на Мастере, что убило игры с влиянием напрочь. Сейчас единственным действенным способом изменения мира является политика. Далёкие от политики согильдийцы жалуются, а им тоже хочется влиять на мир, а не быть балластом.

Пример.
Палач в вольнице. Очень сильно понижает специализацию, но хорошо компенсирует минусы других Мастеров. Мы пытались понизить его влияние, загнали влияние в ближнем круге в минус (0%), но влияние от народа у него оставалось порядка 40k. Для того, чтобы компенсировать это влияние, необходимо минимум четыре(!!!) противника, каждый из которых будет приносить не менее 40k(!!!) отрицательного влияния. Первые три противника будут отапливать космос, всё их влияние будет уходить в ближний круг, где и так уже 0% и ниже не будет, то есть в пустоту, и только четвёртый противник будет понижать влияние от народа. Это слишком сложно и затратно!

**Comment by Tiendil** [comment]
В рамках задачи будут следующие изменения:

- [ ] убираются проекты городов
- [ ] бафаются проекты мастеров
- [ ] помощники и вредители объединяются в общую группу
- [ ] пересматривается размер ближнего круга Мастера (возможно, останется таким же)
- [ ]  влияние героев с предпочтениями начинает засчитываться и во влияние толпы и во влияние ближнего круга

Засчёт влияния героев с предпочтениями как влияния толпы, если не устранит проблему, описанную Argo, то как минимум уменьшит её значимость.

**Comment by Tiendil** [comment]
Вопрос полного убирания влияния народа был рассмотрен.

Влияние народа различается по городам, мастерам, фронтиру/ядру, как в рамках всего мира, так и в рамках каждого города. То есть оно не является полностью случайным, а зависит от выбора игроков. Соответственно, полностью убирать его не целесообразно, что не отменяет возможности совершенствования его механики в будущем.

P.S. Не рассматривал вариант, когда оно является случайной величиной с большой дисперсией. Теоретически такое может быть (например, когда в «народ» входит мало игроков и они выполняют недостаточное количество заданий, чтобы обеспечить равномерное размазывание влияния), но я пока не склонен тратить время на проверку этого случая. Пока считаю, что это не так. Но если кто-то предоставит достоверные расчёты, подтверждающие это, готов рассматривать полное удаление этой механики.
