### ISSUE TITLE
Пользовательское соглашение: изменить пункт про исследование кода

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2114]
Разрешить исследование и поднятие собственных проектов, но запретить модификацию текущего проекта (т.е. хакерство). Но что делать с браузерными расширениями?

**Comment by comtihon** [comment]
`но запретить модификацию текущего проекта` - pr под это попадает?

**Comment by Tiendil** [comment]
Тут имеется в виду проникновение левых людей на сервак и исправление работы кода. Или атака MitM.

Я ещё хорошенько подумаю над формулировкой. Но вообще пользовательское соглашение всё-таки в нашем случае формальность, работа игроков над проектом поощряется.

**Comment by Tiendil** [comment]
Сделано в рамках gh-2384
