### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by comtihon** [the-tale/the-tale#2117]
Рефакторинг кода:
* создать github organization TheTale (репозиториев будет много и они будут теряться в личных репозиториях. Куда удобнее иметь всё в одном месте)
* разнести все под-пакеты из the-tale/src в разные репозитории. У каждого свой setup, свои зависимости (улучшает структуру кода + сразу архитектурно выделяет сервисы)
* для каждого созданного репозитория:
      - сделать своё Readme с описанием что это, для чего и где используется
      - добавить юнит тесты + Travis integration
(упростит проверки, уменьшит время на вникание в код, уменьшит время на отлов багов)
* отделить тестовый код от продового: тесты в `/test`, исходники в `/src`. Структура тестовых пакетов должна повторять тестируемые классы. (уменьшит количество кода в src)
* для главного сервиса добавить полные интеграционные тесты с Travis integration (упростит проверку новых фич)
* разделить backend и frontend на разные репозитории (специализация упрощает код)
* вынести все константы _вроде `('PEACEABLE', 3, 'миролюбивый герой')`_  в базу данных (позволит в дальнейшем легко прикрутить мультиязычность).
* более глубокий packaging (я одобряю package by feature методологию, однако, лучше разбить код на более маленькие пакеты - это способствует более быстрой ориентации в коде), например actions.fightnig (внутри боёвка, всё что с ней связано, pvp, mvp и т.п.)
* помимо package by feature добавить отдельные layer для работы с third party services и вызывать только их (минимизирует количество изменений при замены сервиса, например, при переходе с одной базы данных на другую)
* для каждого пакета и под-пакета маленькое Readme - что это такое, для чего используется, что сюда следует класть а что - нет (упростит разработку для сторонних разработчиков)
* добавить Contributing.md с описанием codestyle проекта, правил принятия фич, необходимыми требованиями (просто для удобства)

Для чего всё это и что в итоге получится?
- быстрое включение для сторонних разработчиков, у которых появилось чуть-чуть времени - быстро найти интересующий пакет, что-то добавить, протестировать и засабмитить
- автоматическое тестирование по открытию pr
- чистая архитектура кода и понятное разделение по функциональности (для разнесение на микросервисы)

**Comment by comtihon** [comment]
P.S. прошу прощения за странную формулировку предложений, последнее время стал хуже говорить про русски.
Кстати, было бы неплохо комментарии и документацию писать на английском (как и саму игру локализовать). Это может привлечь англоязычных контрибьютеров.

**Comment by Tiendil** [comment]
>Кстати, было бы неплохо комментарии и документацию писать на английском (как и саму игру локализовать). Это может привлечь англоязычных контрибьютеров.

Игра текстовая, одна из главных фич — генерация текста. На написание и отладку генератора и редактора фраз ушло несколько месяцев. Поэтому локализация возможна только если появится человек, которые сможет реализовать генератор английского текста, поддерживать его и, желательно, синхронизировать по набору фич с генератором русского текста. На текущий момент это маловероятно и такое направление развития не рассматривается.

>создать github organization TheTale (репозиториев будет много и они будут теряться в личных репозиториях. Куда удобнее иметь всё в одном месте)

Думал над этим. Отложил до момента, когда кто-нибудь сторонний про эту фичу вспомнит. Выпущу ближайшее обновление — создам организацию.

>разнести все под-пакеты из the-tale/src в разные репозитории.

На текущий момент это не принесёт пользы. План развития игры предусматривает этот шаг, но после окончательной её декомпозиции на независимые компоненты. Если сделать это раньше, то будут возникать проблемы с внесением изменений, затрагивающих несколько пакетов, а такие ситуации обязательно будут. Например, сейчас есть пакет tt_web, от которого зависят все новые сервисы, он совсем в зачаточном состоянии и обязательно будет меняться (что потянет внесение правок в остальные сервисы).

Кроме того, выделять имеет смысл всё-таки проекты, которые будут использоваться где-то ещё. Если код используется только вместе с игрой, то удобнее ложить их рядом. Пропадает куча мелких проблем с синхронизацией изменений.

> сделать своё Readme с описанием что это, для чего и где используется

Имеет смысл. Плюс описание API. Могу с этим помочь, но полностью заниматься нет возможности.

> добавить юнит тесты + Travis integration

Тесты везде есть. Интегрировать с Travis или другим CI софтом в текущее время не вижу смысла. Всё равно запускаю и буду запускать все тесты для любого изменения. Делать CI имеет смысл когда есть хотя бы несколько мейнтейнеров.

>отделить тестовый код от продового: тесты в /test, исходники в /src. Структура тестовых пакетов должна повторять тестируемые классы. (уменьшит количество кода в src)

Я такой подход не разделяю (не вижу радикального преимущества по сравнению с текущим). Предпочитаю все семнатически связанные сущности держать рядом — это упрощает работу с кодом. Этот вопрос можно обсудить отдельно.

>для главного сервиса добавить полные интеграционные тесты с Travis integration (упростит проверку новых фич)

см. ответ ранее.

>разделить backend и frontend на разные репозитории (специализация упрощает код)

В конце напишу про предполагаемую архитектуру.

>вынести все константы вроде ('PEACEABLE', 3, 'миролюбивый герой') в базу данных (позволит в дальнейшем легко прикрутить мультиязычность).

Про локализацию уже ответил. Текущий подход к разработке предполагает первоначальное описание всего в коде и вынос в админку только при необходимости частых изменений. Это значительно экономит время на разработку и ввод новых фич (а также на их изменение).

>более глубокий packaging (я одобряю package by feature методологию, однако, лучше разбить код на более маленькие пакеты - это способствует более быстрой ориентации в коде), например actions.fightnig (внутри боёвка, всё что с ней связано, pvp, mvp и т.п.)

Вполне возможно. Готов принимать PR с **обоснованной** перегруппировкой кода. Текущее разбиение на модули сложилось исторически и не всегда удобно. Но специально рефакторить под это дело не вижу необходимости. И главное не удариться в другую крайность, когда под каждые 100 строк делается отдельный модуль.

> помимо package by feature добавить отдельные layer для работы с third party services и вызывать только их (минимизирует количество изменений при замены сервиса, например, при переходе с одной базы данных на другую)

Имеется в виду добавления уровня абстракции для взаимодействия внутренней логики с внешними сервисами? Частично вопрос раскрою далее в описании архитектуры. В общем случае, на текущий момент я склоняюсь к организации кода, которую можно наблюдать в пакетах с именем tt_* в модулях operations.py — т.е. считаю достаточным реализацию фиксированных интерфейсов для взаимодействия с внешними сущностями. Не уверен, что нужно вводить больше абстракции. Можно обсудить более конкретно, но нужен пример.

>для каждого пакета и под-пакета маленькое Readme - что это такое, для чего используется, что сюда следует класть а что - нет (упростит разработку для сторонних разработчиков)

Можно делать для пакетов, выделяемых отдельно (которые в каталоге ./src), для кода в ./src/the_tale это будет делать не очень удобно, поскольку он постоянно внезапно меняется.

Также склоняюсь к тому, что лучше иметь плоскую структуру пакетов и не плодить вложенность.

>добавить Contributing.md с описанием codestyle проекта, правил принятия фич, необходимыми требованиями (просто для удобства)

Это у нас на вики описано. Правда не уверен, что всем видно. Можно перенести из вики в Contributing.md

>быстрое включение для сторонних разработчиков, у которых появилось чуть-чуть времени - быстро найти интересующий пакет, что-то добавить, протестировать и засабмитить

У нас не так много минорных задач, которые можно взять и за пару часов сделать. На мой взгляд проекту нужна скорее подробная вводная по архитектуре и компонентам, что бы после неё можно было сознательно выбирать более серьёзные задачи.

>автоматическое тестирование по открытию pr

Считаю что разработчик должен запускать тесты перед pr :-)

По архитектуре.

Как я говорил, проект движется от монолита к микросервисам. Основных причин подобного движения две:

- сформировавшаяся сильная связанность начала существенно замедлять внесение изменений.
- изначально полностью синхронный код (весь проект на Django) затрудняет реализацию новых фич и усложняет их, плохо сказывается на производительности.

Поэтому переписываю на слабосвязанную асинхронщину.

Рефакторинг ведётся выделением сильносвязанной функциональности в отдельные сервисы с фиксированием API.

Описание того, что должно получиться:

- куча слабосвязанных backed сервисов, не смотрящих во вне (кроме тех, что нужны для работы со сторонними сервисами), предоставляют только API;
- api frontend, который реализует удобное открытое api и не светит структуру сервисов;
- web frontend — сайт игры, по возможности использует api frontend + может обращаться к backed сервисам по необходимости.
- admin frontend — админка, взаимодействует только с backend сервисами.

Один сервис — один Python пакет.

Дополнительно отдельно будут выделены библиотеки:

- tt_web — мини фреймворк для backend сервисов.
- tt_protocol — описание протокола на protobuf.
- tt_logic — непосредственно логика игры: правила, формулы, описания сущностей и алгоритмов. Возможно, будет разбита на несколько меньших библиотек.

Плюс, сейчас выделены в отдельные проекты и репозитории:

- questgen — генерация квестов — будет удалена когда напишу новую версию (будет отдельным сервисом).
- deword — генерация мира — надо влить обратно в общий репозиторий и сделать частью сервиса по работе с картой.
- dext — убогая оболочка над Django — надо влить обратно в сайт и лишний код уничтожить.
- pynames — генератор имён — отдельный законченный проект.
- rels — умные ENUM для питона — отдельный законченный проект, пока ничего удобнее не придумал буду поддерживать.

**Comment by comtihon** [comment]
Считаю, что для ускорения развития игры нужно привлечь больше разработчиков. А для этого нужно улучшить code clearance. 
Для наиболее эффективной разработки нужно применять принцип "Разделяй и влавствуй".
Именно поэтому:
* разделение тестового и src кода критично. Новый разработчик в игре способен охватить взглядом ограниченное количество классов и чем их больше - тем сложнее ему влиться в работу. К тому же - это стандартная (и best practice) на текущий момент структура проектов и может быть привычнее людям.
* разнесение пакетов по разным репозиториям. Также best practice, позволяет ускорить процесс разработки при работе с меньшим контекстом. Позволяет привести базовый репозиторий к стандартному виду (в src только исходники, setup в корне). Поскольку проекты не так зависимы - большого количества изменений, затрагивающих несколько репозиториев сразу быть не должно (если они есть, значит, что-то выделено неправильно).
* интеграция с тестами полезна как и любая автоматизация. Допустим, я вдруг решил попробовать изменить боёвку. Переписал её и что-то не учёл. CI мне автоматически покажет, что часть тестов свалилась (на текущий момент я даже не знаю как, где и какие тесты запустить, было бы неплохо в readme добавить команду для сборки, запуска и тестов + реализовать всё через Makefile)  
Разработчик однозначно должен запускать тесты по pr, однако, это не избавляет от ситуаций, когда он использует зависимость, установленную локально и забывает её прописать. В итоге при деплое всё перестаёт работать (или ещё хуже, деплоится нормально но падает уже в проде при обращении к несуществующей библиотеке)
* интеграционный тест может быть не так важен для монолита, однако, он очень важен для микросервисной архитектуры. Вот [пример](https://github.com/comtihon/surveyor) integration test tool. К тому же - при наличии нескольких разработчиков (а увеличение выработки человеко-часов цель любого opensource проекта) будет просто незаменим.
* про локализацию. Хотя я и считаю, что добавление абстракций (в виде вынесения констант в базу под ключом `ru`) не будет лишним, т.к. даёт возможность быстро добавить новую функциональность без breaking changes, но это дело автора. Однако, я категорически против констант (особенно не вынесеных как константы, особенно в **национальной** локали) внутри кода. Я при собеседовании на работу отклоняю кандидатов с таким кодом.
* про группировку. Не вижу ничего плохого, когда под каждые 100 строк кода создаётся отдельный модуль. Максимальный размер модуля для меня (наибольшая производительность при работе с ним) это 400 строк кода. Группировка (даже если вынесена всего одна функция с 2-4 строк кода) позволяет потом на имеющемся скелете быстро нарастить функционал (если она правильно вынесена, а не overengineering) без breaking changes. Архитектура кода должна быть самодокументирована и должна иметь потенциал для быстрого дальнейшего развития.
* про пакеты и под пакеты. Это полезно для самодокументированой структуры кода. Также это уменьшает количество кода, которое видит новичёк (и шанс вызвать у него панику из-за обилия информации). Например: я хочу добавить новую пассивную способность. Нашёл abilities в `
the-tale/src/the_tale/the_tale/game/abilities/` (считаю, что game это первый кандидат на вынес в отдельный репозиторий, ну может если не первый, то сразу после `tt_` библиотек). Дальше я ожидаю увидеть пакеты `active`, `passive` либо `pease`, `battle/active`, `battle/passive`. Не увидел. Кстати, как и не увидел вообще списка способностей. Похоже не тот пакет?  
Отдельно про плоскую структуру. У плоской структуры есть минусы вроде ограничения развития. Например, все abilities сложены в одном пакете. С развитием игры их становится много. Мы получаем 100+ модулей в одном пакете. Как в нём ориентироваться? Группировка вложенных  модулей позволяет обойти это ограничение. Если разработчику нужно отредактировать одну (или целый класс определённых способностей) ему не обязательно видеть (и вообще знать) о том, что есть другие классы и другие способности.  
Плоская структура кода это одна из причин перехода на микросервисы. Уменьшение количества модулей засчёт вынесения кодовой базы (плоская структура модулей для меня, как архитектора Erlang, особенно больная тема, потому что я вижу, как от этого умирают проекты).
* про абстракцию взаимодействия бизнес логики и внешних сервисов. Да, именно это я и имел ввиду. Есть абстракция storage, к которой обращаются все классы проекта, которым нужен CRUD. Вся внутренняя реализация (подключение к конкретной базы, генерация sql/функции работы с nosql) вынесено в класс, имплементирующий storage. В дальнейшем это позволяет заменить postgresql_storage на mongodb_storage без каких-либо изменений бизнес логики (либо менять их через конфигурацию при старте приложения). К сожалению, я не знаю, как это сделано в текущей реализации, т.к. не нашёл стандартных пакетов `src/database` или `src/services/database` в коде.

По арихтектуре можно отдельно обсудить назначение каждого сервиса + используемые сторонние сервисы. Возможно мой опыт энтерпрайз архитектора пригодится.

**Comment by Tiendil** [comment]
>разделение тестового и src кода критично. Новый разработчик в игре способен охватить взглядом ограниченное количество классов и чем их больше - тем сложнее ему влиться в работу. К тому же - это стандартная (и best practice) на текущий момент структура проектов и может быть привычнее людям.

Как тесты коррелируют с колличеством классов? Не улавливаю нить рассуждения. Если имеется в виду необходимость для понимания фичи читать и код и тесты, то на это никак не влияет положение тестов на файловой системе. Даже наоборот, навигация по коду удобнее, если все интересующие сущности лежат рядом, а не разбросаны по разным иерархиях каталогов. Кроме того, параллельная поддержка согласованности иерархий в тестах и коде сама по себе добавит сложности в разработку. Пока только минусы вижу.

Согласен, что сейчас это наиболее популярный подход, но не считаю его best practice, скорее исторически сложившимся соглашением. Не встречал разбора этой практики с позиции её удобства.

>разнесение пакетов по разным репозиториям. Также best practice, позволяет ускорить процесс разработки при работе с меньшим контекстом. Позволяет привести базовый репозиторий к стандартному виду (в src только исходники, setup в корне). Поскольку проекты не так зависимы - большого количества изменений, затрагивающих несколько репозиториев сразу быть не должно (если они есть, значит, что-то выделено неправильно).

Всё правильно, сначала правильно разделить, потом разнести. Не в обратном порядке. Сначала разделяем по пакетам (в одном репозитории), когда убеждаемся (на практике) что раздление верное, можно разделять репозиторий. 

>интеграция с тестами полезна как и любая автоматизация. Допустим, я вдруг решил попробовать изменить боёвку. Переписал её и что-то не учёл. CI мне автоматически покажет, что часть тестов свалилась (на текущий момент я даже не знаю как, где и какие тесты запустить, было бы неплохо в readme добавить команду для сборки, запуска и тестов + реализовать всё через Makefile)

Документация по запуску тестов и разработке была. Видимо потерялась при переписывании деплоя. Восстановлю в gh-2120. Был уверен, что такая документация есть.

>CI мне автоматически покажет, что часть тестов свалилась

Это же покажет и запуск тестов. Просто нужна инструкция.

>Разработчик однозначно должен запускать тесты по pr, однако, это не избавляет от ситуаций, когда он использует зависимость, установленную локально и забывает её прописать. В итоге при деплое всё перестаёт работать (или ещё хуже, деплоится нормально но падает уже в проде при обращении к несуществующей библиотеке)

Потенциально такая проблема есть, но подобного рода проблемы я предпочитаю решать по их фактическому появлению.

Затраты на поддержку интеграции с софтом для автоматизации окупаются для команд при активной разработке. При неспешной разработке в одиночку — это трата времени. Вход в разработку такой софт не упростит. Будет команда — будет интеграция, а пока тратить усилия на это не хочу.

>Однако, я категорически против констант (особенно не вынесеных как константы, особенно в **национальной** локали) внутри кода. Я при собеседовании на работу отклоняю кандидатов с таким кодом.

Считаю что комментарии и текст нужно писать на языке общения разработчиков (ну и заказчиков). Противоположный подход затрудняет работу. 

>Нашёл abilities
Это способности игрока (кнопка помощи).

>Дальше я ожидаю увидеть пакеты `active`, `passive` либо `pease`, `battle/active`, `battle/passive`
тут: https://github.com/Tiendil/the-tale/tree/develop/src/the_tale/the_tale/game/heroes/habilities

>считаю, что game это первый кандидат на вынес в отдельный репозиторий

Game надо разделить на логику и представление, сейчас они смешаны. Логика вынесется в отдельный пакет, остальное станет частью пакета сайта.

>Отдельно про плоскую структуру. У плоской структуры есть минусы вроде ограничения развития.

Я имел в виду без радикализма. Полностью плоская, конечно, тоже плохо. Но чем меньше вложенность, тем лучше. В противном случае становится сложно вопсринимать зависимости между пакетами.

В большинстве случаев одного уровня вложенности должно хватать. Если не хватает, это повод для пересмотра концепции пакета и возможного его разделения на более специализированные.

>К сожалению, я не знаю, как это сделано в текущей реализации, т.к. не нашёл стандартных пакетов `src/database` или `src/services/database` в коде.

см operations.py в пакетах tt сервисов. Делать именно абстракцию над интерфейсом хранилища не вижу смысла, так как каждое внешнее хранилище имеет свои уникальные особенности работы, которые в универсальном интерфейсе не учтёшь. Поэтому этот слой я делаю для каждого сервиса отдельно с учётом семантики сервиса. Если потребуется переключаться на другие хранилища, переключение будет происходить на уровне конкретных сервисов, а не их интерфейсов.

>По арихтектуре можно отдельно обсудить назначение каждого сервиса + используемые сторонние сервисы. Возможно мой опыт энтерпрайз архитектора пригодится.

Каких-то особых вопросов по сервисам я сейчас не вижу. Их границы выделяется естественным образом. Проблема в том что некому этим заниматься :-)

Есть несколько ожидаемых «проблем» в будущем, связанных с отображением отношений между сущностями игры для игроков (не в самой игре, а в сопровождающей инфраструктуре: фольклоре, форуме, etc). Но обсуждать их имеет смысл только в случае реализации, иначе лягут в долгий ящик. К этому же можно отнести и необходимость появления нормальной CMS.

**Comment by Tiendil** [comment]
Закрываю, так как обсуждение закончилось. По итогам обсуждения создано несколько задач.
