### ISSUE TITLE
Рынок: ограничение явной передачи карт

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2129]
Через рынок можно "передавать карты" заранее договорившись о времени передачи. В этом случае платится минимальная комиссия и нарушается баланс игры. Необходимо прекратить или усложнить эту практику. 

Варианты:

- минимальная цена для карт разной редкости.
- встраивание игрового бота, который будет скупать дешёвые редкие карты и продавать их дороже.
- случайные задержки для появления карт на рынке (чтобы нельзя было договориться о времени их появления).

**Comment by ArgoTheTale** [comment]
Свой бот – лучшее решение. При этом лучше не торговать скупленными картами, а просто выводить их из игры. Можно даже сделать бота и его предложения открытыми. Эдакий сервис обмена карт на печеньки по низкой цене, но зато гарантированно и мгновенно.
Устанавливать жёсткие цены на карты – не лучшая затея. Пусть они формируются естественным образом. Случайные задержки тоже не спасут в случае, если кто-то из пользователей сам напишет бота (при этом один игрок оказывается в явной выгоде по отношению к остальным, что не есть хорошо).

**Comment by Tiendil** [comment]
Свой бот — самое сложное и спорное решние. И он точно не должен просто выкупать карт, так как это приведёт к бесконечному потоку печенек для вечных подписчиков.

**Comment by ArgoTheTale** [comment]
Признаю, сглупил.
А что если рынок попросту будет блокировать лоты, цена которых явно ниже средней цены на рынке, не давая выставить карту на продажу? При вычислении этой средней цены придётся регулярно отбрасывать старые значения, также не стоит учитывать лоты, которые были закрыты менее чем за 10  (2, 5) минут после выставления карты на продажу (чтобы исключить из выборки обязательные случаи прямой передачи), и возможно будет разумным отбрасывать несколько крайних значений (самых дешёвых и самых дорогих), чтобы торговцы не могли несколькими хитрыми лотами сбить бота с толку и манипулировать естественными ценами.
Единственно придётся отключать этого бота в том или ином случае, если выборка цен по определённой карте ещё недостаточно большая, чтобы дать возможность сформироваться актуальной цене после введения новой карты или ребаланса старой. То есть возможен момент, когда для каких-то карт бот будет работать, а для каких-то нет.
То есть вариант первый, но минимальная цена не строго фиксированная, а плавающая, поскольку вычисляется автоматически из логики рынка.

**Comment by Tiendil** [comment]
Вполне себе вариант, но требует очень аккуратной проработки.

**Comment by Vishoz** [comment]
Ну так и нет никакого интерфейса передачи карт в тех же гильдиях. Зачем мне передавать карту по полной цене согильдийцу, если она будет использована во внутригильдийных целях?
Вот кстати, на будущее обновление с гильдиями, как ты смотришь на создание гильдийного хранилища карт?

**Comment by Tiendil** [comment]
На текущий момент в игре не предполагается никакого явного обмена картами между игроками - это была бы оргомная дыра в балансе для ботоводов. Соответственно, какая-либо передача карт через гильдию тоже не рассматривает.

**Comment by Vishoz** [comment]
Жаль. А ботоводы - это, в принципе, огромная дыра в балансе.

**Comment by Tiendil** [comment]
Скорее это объективная реальность, в которой приходится жить.
