### ISSUE TITLE
Добавить в меню «Сообщество» ссылку на телеграмм Пандорийской газеты

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2141]

**Comment by Nevardas** [comment]
Подумалось тут, что лучше всё-таки на форумную тему, как с темной темой сделано.
Из одной только ссылки на канал не будет ясно, что я не в только в телеграме информацию вывешиваю.

**Comment by Tiendil** [comment]
Добавил ссылку на телеграм-канал. Кому надо, тот найдёт тему на форуме. Пользователи Вконтакте и так увидят посты.
