### ISSUE TITLE
Карты Судьбы: увеличть редкость карты создания гильдии

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2151]
Игроки создаёт по несколько гильдий в день. В большинстве из них только один член.

**Comment by Delargond** [comment]
А смысл? Не важно, синяя или зеленая карта была использована, игроки всё так же будут создавать гильдии для себя. Я бы вообще этой карте обычную редкость влепил.  Пользы от нее вообще никакой. Синяя же она ещё и будет мешать получить полезные карты, такие как "новый путь" или "магический вихрь".

**Comment by Vishoz** [comment]
Только не легендарной редкости, пожалуйста :))

**Comment by Nevardas** [comment]
А что если сделать так, чтобы эта карта не падала тем, у кого есть гильдия? ну или, на крайний случай, у кого уже есть одна такая карта на руке или в хранилище? тогда вообще без разницы будет какая редкость

**Comment by Tiendil** [comment]
Много мёртвых гильдий плохо скажется на игре. Хотя бы потому, что новые игроки будут видеть в этом разделе печальнку картину.

**Comment by Delargond** [comment]
Не с тем ты борешься. Если хочешь только уменьшить количество мертвых гильдий, то повышение редкости несомненно замедлит этот процесс. Но это не решение проблемы, а лишь оттягивание ее решения. Гильдии всё равно будут появляться. И появляться они будут мертвыми, как и сейчас. Мне, как одному из активных игроков, до фонаря, сколько там у нас мертвых гильдий. Но мне не безразлично, что я получу в итоге объединения трех необычных карт. Если человека зацепила игра, то он в ней останется, а если нет, то никакое количество гильдий не повлияет на его выбор. Я и ещё многие пришли сюда, когда многих текущих фич не было, и при этом остались.  Новые игроки. Сколько их уже было в 2015, 2016 годах. Как пришли, так и ушли. Они даже не заметят тех изменений, которые ради них делают (в частности о повышении редкости "братства" говорю). А вот тем, кто сюда регулярно заходит, придется "радоваться" такому повышению и мириться с ним ещё n-ое количество времени.  Нужно гильдконтент подвозить, добить уже наконец 0.3 версию. Заняться гильдиями, и тогда они не будут мертвыми. В игре и так нормальных и интересных карт мало. Штуки три-четыре. Не хочешь интересные карты завозить (да, я опять про "склеившиеся карты" ), которые бы привносили какой-то новый опыт и эмоции, а не сухие "+N к какому-то параметру" , так ещё и это гуано в ценности повышаешь. Грустно всё это.

**Comment by Tiendil** [comment]
Поэтому я не повышаю редкость до легендарной или вроде того.

**Comment by ArgoTheTale** [comment]
Мёртвые гильдии не проблема. В той же Lineage 2 гильдию из одного человека мог создать любой желающий, накопив лишь немного монет и опыта, а затем прокачивать её, открывая новые плюшки и возможности для созданной гильдии, но выполняя каждый раз всё более сложные условия. Как результат – мёртвых гильдий первого-третьего уровня на старых серверах были сотни, а затем и тысячи. Но это никому не мешало, ибо гораздо нагляднее были заметны цели и свершения гильдий крупных и активных: их ругань друг с другом в геройском чате на весь мир, ежедневная олимпиада с перетягиванием каната и борьбой за эти самые геройские статусы, осады замков раз в две недели с массовыми пвп 200 на 200 тел в урожайный день, постоянная возня на популярных местах кача, круглосуточный караул случайного респа эпических рейд-боссов, борьба за уникальные ресурсы и так далее. На неудачников, захотевших бегать под своим собственным флагом и не осиливших растущие с каждым уровнем гильдии требования к её развитию, смотрели как на умалишённых.
Я это всё к чему... Правильно вверху говорят: надо завозить гильдконтент. Его наличие сделает проблему мёртвых гильдий совершенно незначительной.
