### ISSUE TITLE
Карты судьбы: карты на увеличение опыта спутника

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2192]
Стоит ли делать легендарную карту на полную прокачку спутника или только на 50%/25%?

**Comment by Nevardas** [comment]
имхо
если вводить легендарку на полную прокачку, то разумнее ей будет пользоваться сразу, как только активируется карта на спутника. Не думаю что будет очень много людей, кто будет чередовать нескольких спутников, потому скорее всего карта будет полезна где то на среднем-последнем этапе развития спутника, а значит полезнее будет ввести разные градации этого типа карты, но не более чем на 50%-60%

к тому же, зачастую последняя способность спутника открывается гораздо раньше 100 уровня. если не всегда.

**Comment by ArgoTheTale** [comment]
Бонус можно сделать не процентным. Как мы знаем, для каждого последующего уровня слаженности требуется выполнить всё больше заданий. Карты можно привязать к этим самым заданиям. 5050 (полная прокачка) за легендарку, ~1450 за эпик, ~410 за редкую, ~115 за необычную, ~30 за обычную.

Будут полезны и обычные карты, чтобы быстро открыть первые полезные способности у только что полученных спутников, и самые последние, чтобы сразу получить полностью готового спутника для какого-нибудь ивента.

**Comment by Delargond** [comment]
> 5050 (полная прокачка) за легендарку, ~1450 за эпик, ~410 за редкую, ~115 за необычную, ~30 за обычную.

Это геморрой какой-то будет. Лучше проценты делать, т.к. если спутник, к примеру, уже имеет 90 слаженности, то какой прок игроку будет от обычной карты? Она даже 1 слаженность не даст. Если ввести процентное повышение, то даже черные и зеленые карты будут полезны, а не превратятся в очередной хлам для переплавки.

**Comment by ArgoTheTale** [comment]
Проценты можно абузить, приберегая дешёвые карты на поздние стадии прокачки спутника, а чистые цифры нет. Баланса больше в моём варианте.

**Comment by Delargond** [comment]
Не понимаю, откуда в некоторых игроках желание ставить самому себе палки в колеса. О каком абьюзе может идти речь? Так и вижу бандитов-рецидивистов, которые видите ли посмели с выгодой для себя прокачать спутника на последних уровнях слаженности на 1 или 2, тем самым лишив себя примерно месяца "удовольствия" от наблюдения за скучной и нудной прокачкой спутника. Арго, ты видишь статистику, которую Спайк собирает ежемесячно? Ты видишь полудохлый форум? Людей нет. В игре жуть как медленно и скучно всё происходит. Ждать два-три месяца, пока спутник прокачается - это п****ц, на мой взгляд. Тут реально со скуки сдохнуть можно, при этом в той другой игре герой сам без моей помощи уже и храм построил, и половина ковчега готова. Про баланс вообще смешно слушать. Тут деньги решают, кому как ни тебе это знать.

**Comment by ArgoTheTale** [comment]
Даже обычные карты в моём варианте могут быть полезны любому игроку, если поставить цель сплавить из них одну легендарку на чёрный день. А несбалансированная халява популярность игре не принесёт. Вариант с процентами, конечно, не карты конвертации опыта в энергию, но одного поля ягоды.

**Comment by Vishoz** [comment]
Полную прокачку, имо, добавлять не нужно. Проще использовать мелкие карты для необходимой прокачки. Пока обычный игрок соберет легендарку, он уже успеет прокачать спутника.
