### ISSUE TITLE
Если герою в рюкзак не помещается лут, необходимо выкидывать самый дешёвый лут и заменять на новый

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2208]
- Если непомещающийся лут хуже всего лута в рюкзаке, не берём его и пишем фразу как и сейчас.
- Если непомещающийся лут лучше чем худший в рюкзаке, то выкидываем худший лут в рюзкаке и пишем фразу (надо добавить) о том, что один предмет в рюкзаке заменён на другой.
- артефакт всегда считаем лучше хлама.
- артефакты сравниваем по полезности для героя (если рюкзак забит артефактами).
- убираем кнопку выкидывания лута.
- убираем рейтинг подарков.

P.S. При выпуске обновления с этим надо будет добавить несколько фраз нового типа.

**Comment by ArgoTheTale** [comment]
Good first issue?

**Comment by Tiendil** [comment]
Добавлю, но возможно я быстрее это сделаю, чем кто-то заметит :-)
