### ISSUE TITLE
Рынок: уровнять возможность получения профита от продажи карт игроками

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2229]
Сейчас, если один игрок выставит много одинаковых карт  на продажу, он может на долго перекрыть другим игрокам возможность продавать свои карты. Потому, что в 1-ую очередь будуь продаваться его карты.

Необъодимо добавить эвристику в выбор карт для продажи, которая предотвратит это.

Варианты:

1. Выбирать список игроков, продающих карты, и брать карту от случайного игрока.
2. Выбирать карты так, чтобы среди N последовательных продаж не было карт от одного игрока.
3. что-то ещё.

**Comment by Vishoz** [comment]
> Необъодимо добавить эвристику в выбор карт для продажи, которая предотвратит это.
И необходимо описать эту эвристику в доступной форме для игроков, чтобы не возникало лишних вопросов.
