### ISSUE TITLE
Перевод печенек ограничить только купленными печеньками

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2247]
Варианты:

- лучший: при покупке указывать какому игроку в подарок покупается
- разрешить переводить не больше чем куплено в последней транзакции
- разрешить переводить не больше чем куплено за последний месяц
- худший: разрешить суммарно переводить не больше чем сумма всех купленных печенек (за всё время)

**Comment by Nevardas** [comment]
Аналогично, не совсем понимаю для чего и чем обусловлено.
Игрок заработал печеньки на торговле картами, почему ему становится нельзя их передать, а можно только купить подписку и другие карты? вечникам так вообще только карты и остаются. Благотворительность единственный разумный вариант "вложения валюты".

**Comment by Tiendil** [comment]
Это один из пунктиков в совершенствовании модели монетизации игры. Вообще, все переделки рынков и печенек связаны с тем, что я пытаюсь сделать максимально честную и максимально стабильную (с точки зрения баланса) систему монетизации. Поскольку пункты местами взаимоисключается, приходится искать баланс между «всё разрешить» и «всё запретить».

Передача печенек была реализована раньше рынка и не предполагалось, что можно будет напродавать карт и передать печеньки другим аккаунтам. Эта возможность сильно облегчает жизнь твинководам. Несмотря на то, что твинки разрешены, полезными для игры я их не считаю.  

Операции с рынком должны быть направлены на развитие своего аккаунта, а не на момощь другим. Передача же печенек должна решать в первую очередь редкую помощь согильдейцам или друзьям, а не планомерное развитие других аккаунтов.

**Comment by Vishoz** [comment]
> Операции с рынком должны быть направлены на развитие своего аккаунта, а не на момощь другим. 

Так нечего развивать то... Моему герою никакие карты уже не нужны.
А еще, этим ты поставишь крест на пользовательских конкурсах с наградами в печеньках, ну или придется тебе самому их передавать...
И вообще, даже если ты совсем закроешь передачу, все равно не поможет, просто будет дороже.

**Comment by Tiendil** [comment]
>А еще, этим ты поставишь крест на пользовательских конкурсах с наградами в печеньках, ну или придется тебе самому их передавать...
Раньше так и делал. Не особо напрягало меня это.

**Comment by Vishoz** [comment]
Если бы не напрягало, то и передачу бы не делал, хых ))
Но не суть. Даже полное закрытие функции передачи печенек не помешает твинководам их передавать. Будет чуть неудобнее, только и всего.

**Comment by Tiendil** [comment]
Небольшая статистика:

```
total 4216 transactions
total cookies 992999 (~165 infinit subscriptions)

senders 224 (infinits: 116, buy: 160)
recipients 390  (infinits: 149, buy: 202)
total 447 (infinits: 167, buy: 250)
recipients & senders 167

buy - to > 0: 182
buy - to > 0 and to > 0: 134
buy - from > 0: 201
buy - from > 0 and from > 0: 111
to > 0 and from > 0: 167
to - from > 0: 318
buy > 0 and to > 0 and from > 0: 112
buy == 0 and to > 0 and from > 0: 55

infinit: 336

infinit received more then infinit price: 79 (~24% from all subscriptions, ~48% from all cookies)
infinit send more then infinit price: 27 (~8%)
```

В итоге решение будет следующее:

Перевести другим игрокам в сумме можно не больше, чем сумма купленных напрямую печенек минус цена вечной подписки.

С таким правилом:

- Любой игрок может свободо покупать печеньки для других игроков.
- Фармить вечную подписку (купив одну, и сливая карты на рынке) не получится.

**Comment by SilentWrangler** [comment]
Не получится? Ой да ладно! Передаём стартовый капитал и начинаем циклить бывших советников например или иную редкую никому не нужную карту. Купил за 10, выставил за 6000, выкупил передатчиком.

**Comment by SilentWrangler** [comment]
На самом деле фарм вечек усложнился ненамного, а вот некарточно-торговые операции между живыми игроками ты усложнил.
Я вот недавно устраивал благотворительность по новичкам с ранеными эмиссарами:
https://the-tale.org/forum/threads/3737?page=73#m251972
Теперь для повторения мне потребуется закупаться.
Теперь чтобы заплатить магистру другой ги за отступные с города, я не смогу потратить заработанное на рынке.
Теперь чтобы договориться с живым игроком об анонимном привете  полувражескому эмиссару, мне потребуется возиться с картами.
