### ISSUE TITLE
Карты судьбы: поправить карты прямого начисления влияния

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2264]
Дополнить описание перечнем модификаторов, которые должны влиять на начисляемое влияние.
Дописать тесты, которые будут это проверять.
Должны ли хоть какие-то модификаторы влиять на эту величину? В текущий момент получается, что есть карты на влияние в задании, на которые действуют все бонусы и штрафы. А есть карты прямого влияния, которые, по идее, должны просто гарантированно давать указанную сумму.
Возможно, надо изменить количество начисляемого влияняи, чтобы компенсировать отсутствие бонусов.

**Comment by ArgoTheTale** [comment]
"Возможно, надо изменить количество начисляемого влияняи, чтобы компенсировать отсутствие бонусов."
Тут важно ещё учесть карты на известность. Как вариант совсем убрать их, если значения карт прямого начисления влияния станут равны или выше значений карт на известность. Ибо единственным плюсом у карт на известность в этом случае станет маскировка

**Comment by Tiendil** [comment]
В итоге добавил в описание карт следующую фразу: 

```
Влияние засчитывается напрямую, без бонусов и штрафов от чего либо. Известность героя не меняется.
```
