### ISSUE TITLE
Удалить Dockerfile

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2272]
Так как уже не поддерживается.

**Comment by serhii73** [comment]
@Tiendil Hi. Just `del Dockerfile`? And all?

**Comment by Tiendil** [comment]
@serhii73 Hi. 

And check if there are exists other deprecated configs from old deploy procedures (related to docker). (There was few commits done, related to docker in 2015-2017 years)

**Comment by serhii73** [comment]
@Tiendil Do you mean https://github.com/the-tale/the-tale/commit/08a945c7a426df68e8b7e9792e1dd898abf1a84b this commit? Right?

**Comment by Tiendil** [comment]
Right
