### ISSUE TITLE
Карты Судьбы: улучшить выдачу "подписочных" карт

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2280]
Сейчас, покупая подписку, игрок начинает получать карты, которые большинству не нужны. Необходимо переботать механизм выдачи карт, чтобы игроки не расстраивались и новые карты действительно были бонусом.

Варианты:

1. По таймеру на каждый тип карт.
2. По одному таймеру подписчикам давать две карты: обычную и подписочную (оставлять ли ускоренное получение карт для подписчиков или хватит возможности переработки подписочных карт?)
3. Кнопка переключения режимов получения карт: только обычные, только подписочные (?), оба типа.

**Comment by Nevardas** [comment]
не вижу особой разницы в вариантах. и так и так подписчики получают выгоду в плане фарма карт... но два таймера выглядят уж слишком замороченно, потому второй вариант гораздо привлекательнее. 
ускоренное время стоит оставить, ибо подписочных карт не так уж и много у нас сейчас а выгода от фарма не такая существенная как может покажется: игроку все равно придется надеяться на рандом при превращении.   вот если бы была половина крат такая, а половина обычная, тогда бы вопрос времени стоял острее.

**Comment by Tiendil** [comment]
Если оставить ускорение таймера, то в итоге скорость получения карт будет ещё x2 от существующей, потому что вместо одной 2 карты будет. Это, на текущий момент. выглядит перебором.  Обойти это можно нерфом подписочных карт, но это тоже плохой вариант.

**Comment by Nevardas** [comment]
Объединение подписочных карт только с подписочными? лучше, но не сильно, ибо карт таких мало. только надеяться на рандомное превращение, а не рецептное, которое в теории может дать нормальную карту.

Галка на разрешение получения подписочных карт? опять все упирается в их количество. надо придумать карту, а лучше несколько, которые и правда будут полезны именно подписчику, дабы оправдать настройку и чтоб хоть кто то ставил эту галку. однако у нас и без того засилие карт..

это я к тому, что в любом варианте есть минусы. надо только найти где минусы не такие существенные.

**Comment by vBAZIL** [comment]
а почему нельзя подписчикам дать на выбор те типы карт которые они хотят, только выбор сделать нормальным,
Золото
Влияние
Вещи
движение
бой
и т.д. какие типы решат разработчики/балансировщики так же обязателен минимум 2-5 категорий
и давать ОДНУ карту как сейчас но из выбранных категорий, вот и бонус подписчикам

**Comment by Tiendil** [comment]
> а почему нельзя подписчикам дать на выбор те типы карт которые они хотят
- это усложнит баланс
- это усложнит реализацию
- это усложнит взаимодействие игроков с игрой (надо будет объяснить где и как это настраивать, игроки будут забывать о том что настроили и ждать карты, которые не могут получить, etc).

**Comment by vBAZIL** [comment]
тогда убрать "карты судьбы получаются в 1.5 раза быстрее;" и давать две карты подписочные и обычные смотрится неплохо

**Comment by Nilsden** [comment]
> Галка на разрешение получения подписочных карт?

Считаю это одним из правильных решений. Не нужно изобретать велосипед с новыми таймерами и т.д. 

Ну и раз уж тут мозговой штурм и "decision required" предложу близкую альтернативу: галка на разрешение получения подписочных карт **в результате объединения карт**. Я уже пару раз негодовал на форуме из-за того, что получал подписочные карты из "белой полосы" и в награду за фразы лингвистики из-за кривой реализации выдачи карт. Но время показало, что зря я так сильно переживал. На данный момент, будучи неподписчиком, я не могу получить карты подписчика при объединении карт, следовательно, я со спокойным сердцем объединяю всякие там "должки мастеровых" и тому подобные, ибо знаю, что зелёная карта будет "неподписчицкая". И даже если рандом сразу присылает мне фиолетовое "благословение Дабнглана" в награду за фразу я тоже спокойно объединяю его в легендарную, т.к. знаю, что легендарная будет "неподписчицкая".

**Comment by Tiendil** [comment]
Всевозможные галочки мне очень не нравятся.

Пока, с точки зрения интересности и удобства, вижу такой вариант:

1. Карты делятся на обычные и мировые (те, которые сейчас доступны только подписчикам).
1. Все игроки получают обычные карты по таймеру.
2. Подписчики получают дополнительную мировую карту вместе с обычной.
3. Если объединяются только обычные карты, то будет получена обычная.
4. Если объединяются только мировые карты, то будет получена мировая.
5. Если объединяются и обычные и мировые карты, то может быть получена карта любого типа.

Главный вопрос тут - баланс. Разделение на две группы сильно упростит фарм карт, так как при объединении значительно возрастёт шанс получить нужную карту.

Плюс, названия нужны более инетерсные :-)

**Comment by SilentWrangler** [comment]
Может, при выдаче карт спрашивать подписчика, сколько гарантированно неподписочных карт он хочет? Выдаётся 7 карт, игрок указывает 4. 4 гарантированно будут неподписочными, 3 случайными.

**Comment by Mefi13** [comment]
Считаю, что нет смысла что-то менять. 

> Сейчас, покупая подписку, игрок начинает получать карты, которые большинству не нужны. Необходимо переботать механизм выдачи карт, чтобы игроки не расстраивались и новые карты действительно были бонусом. 
Такое можно сказать и про карты для неподписчиков, что они не нужны, и атких тоже много. Если игроки не понимают возможностей карт, это не значит, что они бесполезны. К тому же у них есть особенность _продаваемые_ и они всё также могут быть _перекрафчены_.

Последнее обновление увеличило награды в лингвистике. Как по мне, это решение текущего каприза игроков "не хочу получать ненужные мне карты". Теперь проще игрокам крафтить карты из полученных продаваемых и надеяться на выпадения _нужных_ для их игры карт

К тому же в одной задаче планировался уникальный крафт, аля дейли предложение. Это тоже добавит интерактива и ненужные карты станут нужными.

**Comment by Nilsden** [comment]
> Такое можно сказать и про карты для неподписчиков, что они не нужны, и таких тоже много.
Можно. Но в случае с подписчицкими картыми я могу твёрдо утверждать, что они ВСЕ мне не нужны. ВСЕ.

> Если игроки не понимают возможностей карт, это не значит, что они бесполезны. К тому же у них есть особенность _продаваемые_ и они всё также могут быть _перекрафчены_.

Вы напоминаете типичного представителя форума рунета. Когда на форуме объект А спрашивает и/или просит совет, появляется объект Б, который начинает упорно убеждать, что ответ и/или совет объекту не нужен вовсе и рекомендует всё вообще иначе делать. В вашем же случае вы явились в тему обсуждения проблемы и пытаетесь доказывать, что ее нет. Жесть)

Когда у меня не было подписки, получение карт было одним удовольствием. Практически всё, что получалось, можно было использовать для развития или настройки героя. Получение подписки же  принесло с собой "домовых", "спокойствия" и прочую дрянь. Эта ерунда не имеет к герою никакого отношения. Эти карты для меня БЕСПОЛЕЗНЫ. Если они вам нужны, прошу на рынок, там весь этот хлам по мелочи выбрасываю. Так вот ведь беда: не берут. За полсотни, а то и за сотню предложений некоторых карт перевалило. Но не берут. А переплавлять одно говно и надеяться, что не выпадет другое, хотя чаще всего так и получается - сомнительное удовольствие. Лично меня более чем устроит, если мне вообще перестанут выдавать карты подписчиков, т.к. **ни одна из них не идет рядом с моими интересами в игре**. В игре ВСЕ подписчицкие карты направлены на тех, кому интересна Карта и Книга Судеб. Ошибочное мнение, что подписку покупают только ради "политиканства", слишком глубоко укоренилось в некоторых головах. В игре есть РАЗНЫЕ типы игроков и интересы у них разные. Попытки кого-то в чем-то переубедить - пустая трата времени. Я купил, чтобы **поддержать проект и его создателя**, но в награду получил неприятный осадок, разочарование, назовите это как хотите. Появление "домовых" и т.д. при получении карт - каждый раз разочарование. Ради этого я подписку купил? Зашибись награда.

**Comment by Mefi13** [comment]
> Но в случае с подписчицкими картыми я могу твёрдо утверждать, что они ВСЕ мне не нужны. ВСЕ.

У вас претензия уровня "я так хочу"(точнее не хочу), когда по этому вопросу (по поводу полезности карт) есть более глобальные проблемы и возможности решения. Появление галки у подписчика появится возможность увеличить шанс получения карт с вышей валидностью, что тоже не есть правильным.

> Считаю, что нет смысла что-то менять.

Тут я поспешил, этот ответ относился конкретно к галке. К таймерам, предложенным Тиендилом ни претензий, ни полезных мыслей нет.

**Comment by Tiendil** [comment]
В итоге склоняюсь к переключателю режимов получения карт с тремя режимами:

- только обычные
- только мировые
- любого типа
