### ISSUE TITLE
Эффект артефакта «особая аура» распространяется только на поднятый лут

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2298]
Небходимо либо уточнить описание (и, возможно, усилить) либо распространить на другие способы получения артефактов (карты, покупка, кузнецов)

**Comment by Nevardas** [comment]
мне кажется, что стоит расширить на покупку, по черте характера, за награду в квестах (в том числе и по квесту помощи кузнецу), но при этом не трогать арты, которые прямо можно получить через карты (всякие внезапные находки). возможно даже стоит понизить эффект до единицы только в одной из сил (магу в магии, воину в физике, авантюристу рандомно) 
распространение на поднятые с земли вещи, даже с учетом увеличения эффекта, не солидно для эпика)

**Comment by Mefi13** [comment]
Было бы неплохо некоторые задачи из тегов est_simple и good first issue  постепенно закрывать, особенно с type_bug.
На карты (внезапные находки и вся их серия) не стоит распространять, ибо p2w.

**Comment by al-arz** [comment]
Наткнулся на форуме на [упоминание ](https://the-tale.org/forum/threads/9088?page=10#m257709) этой проблемы, решил посмотреть. Мне, как новичку, чтобы понять в чём проблема, не хватило описания самого эффекта, так что [вот](https://the-tale.org/guide/artifacts):  "Особая аура - Физическая и магическая сила всех артефактов, получаемых героем, увеличивается на 1".

**Comment by Tiendil** [comment]
Эффект уже распространён на все артефакты
