### ISSUE TITLE
Способность спутника "Тихий"

### ISSUE THREAD

**Issue by devapromix** [the-tale/the-tale#2299]
Способность спутника "Тихий" - героя и его спутника меньше замечают враги, так как они передвигаются тише. Как способность конструктов "Шумный", но наоборот. Есть похожая способность "Острый глаз" - издали высматривать врагов и заблоговременно избегать встречи с ними. Но это не то. Больше всего подходит ворам и т.п.

**Comment by Tiendil** [comment]
>Но это не то
По-моему как раз то. Эффект на игру будет такой же. Плодить одинаковые механики с разными названиями — только путать игроков.
