### ISSUE TITLE
Ограничить максимальную безопасность в 95%

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2308]
Или на сопоставимую величину.  100% потенциально может сломать баланс и ломает опыт игры новичков, так как они не видят боёв, появляясь в безопасном городе

**Comment by ArgoTheTale** [comment]
Ну вот зачем?
Как появится игрок в абсолютно безопасном городе, так и выйдет из его пределов через несколько минут и напорется на монстра уже в окрестностях другого. Какие проблемы? Учитывая ограниченные ресурсы по Мастерам и сильно занерфленные проекты, сделать много абсолютно безопасных городов всё равно невозможно, а пара таких баланс не ломают, но добавляют интереса игрокам.

**Comment by Vishoz** [comment]
Согласен. В конце концов, можно прописать эксепшен для новичков, понижая только им безопасность, если она больше 95%.

**Comment by SilentWrangler** [comment]
Чем отсутствие боёв "ломает" опыт игры новичкам? Тем, что они не видят, как их герой мееедленно ковыряет каждую крысу по (сколько там ожидается ходов для "не перекачанного" героя,10?) полторы минуты, а крыс этих десятки?
ИМХО, опыт игры новичку может сломать "мой герой застрял на клетке и постоянно дерётся", а не обратное...
Вообще, бои должны быть только квестовые, а безопасность должна регулировать их сложность.

**Comment by ArgoTheTale** [comment]
> Согласен. В конце концов, можно прописать эксепшен для новичков, понижая только им безопасность, если она больше 95%.

Можно просто прописать дополнительное условие для выбора появления стартового города у новичка: наиболее безопасный, но с безопасностью не выше 95%. Если это **настолько** важно!

**Comment by Tiendil** [comment]
С появлением gh-2470 значительно повышается актуальность.
