### ISSUE TITLE
Города: переработка зданий

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2314]
На карте появилось слишким мгного строений с прочностью 0%. Необходимо добавить стимул для разрушения таких построек.

Полезное обсуждение тут: https://the-tale.org/forum/threads/7652

**Comment by Nevardas** [comment]
Лучше бы еще интерфейс починки поправить, сделав возможность чинить из строения. А то сейчас пока в одном месте название найдешь, пока во втором...

**Comment by Tiendil** [comment]
В итоге:

- переключаем здания на поддержку от производства города
- амортизация пропадает
- дары хранителей будут удалены
- карты даров и ремонта будут убраны из игры (заменены на что-нибудь полезное)
