### ISSUE TITLE
Карты судьбы: карты на задание города / эмиссара

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2348]
- эпическая (?): случайное задание, связанное с выбранным городом, 3 карты объединяются в следующую
- легендарная (?): случайное задание, связанное с выбранным Мастером

Доступны только подписчикам.

Карты на известность и карты на прямое влияние удаляются из игры.

Карты аналогичной (с новыми) редкости, доступные для продажи на рынке, заменяются на новые.
Остальные карты заменяются на случайные.

**Comment by ArgoTheTale** [comment]
Карта помощи/вреда эмиссару: чёрная.
Карта помощи/вреда Мастеру: легендарная.

Мне одному кажется, что тут какая-то слишком большая пропасть?
