### ISSUE TITLE
Карты Судьбы: карты серии «интриги» сделать доступными только для подписчиков

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2357]
Для неподписчиков они несут мало пользы.
С другой стороны это (возможно) не согласуется с текущей логикой отнесения карт к подписочным (только карты, влияющие на мир).

**Comment by ArgoTheTale** [comment]
Мне, как мультоводу, покупающему дополнительные голоса по мере надобности, удобнее, когда такие карты падают в том числе и неподписчикам. Нет нужды прибегать к передаче карт через рынок. Просто оплачивается подписка на любом твинке — и всё. Отказ от выдачи этих карт не подтолкнёт мультоводов пользоваться рынком, а заставит иметь отдельную группу твинков на каждый город в игре.

**Comment by Tiendil** [comment]
Закрыто в пользу gh-2373
