### ISSUE TITLE
Помощь в проекте

### ISSUE THREAD

**Issue by serhii73** [the-tale/the-tale#2364]
Здравствуйте, я новичок в джанго и хотел бы позакрывать ишью в вашем проекте, у вас есть ишью для новичков?(видимо они помечены гуд ферст ишью=))
С какого ишью порекомендуете начать?

**Comment by Tiendil** [comment]
Добрый день.

Инструкция как влиться в разработку есть в нашей документации: https://docs.the-tale.org/ru/stable/development/how_to_start.html

Почитайте её, там немного подробнее расписано что можно делать.

Когда почитаете, попробуйте сформулировать более чётко чем хотите заниматься: что в Django больше всего интересно и какой частью игры хотелось бы заниматься (проект большой и задачи можно выбрать под разные хотелки).

Изучите задачи по метке good first issue.

После этого напишите мне в личку желаемое направление работ и желаемые задачи (если есть). Также напишите сколько времени в неделю можете тратить на работу и какой опыт у вас уже есть. Я помогу сориентироваться (и может быть предложу что-нибудь ещё).

Мои контакты можно найти тут: https://tiendil.org/about/ используйте любой
