### ISSUE TITLE
Карты Судьбы: ребаланс карт на известность.

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2373]
Сейчас карты дают слишком большую фору твинководам, так как падают часто и имеют сильные эффекты. Позволяют быстро переводить твинков из города в город. Надо что-то с этим делать.

Варианты:

- Полностью убрать этот эффект, избрав путь хардкора.
- Значительно снизить их силу в 10 раз или более.
- Убрать низкоуровневые карты, высокоуровневые понерфить.

Также рассмотреть делание этих карт чисто подписочными. В контексте gh-2357

**Comment by ArgoTheTale** [comment]
Ни один из вариантов не поможет, а лишь спровоцирует ещё больший упор в твинков. У твинководов появится по N штук твинков на каждую пару-тройку важных для них городов в игре (по предпочтениям родного города, соратника и противника). В нужный момент будут оплачиваться подписки ключевой группе (и отдельным твинкам из соседних групп, которые тоже будут иметь целевой город в топ-10), что позволит добиваться желаемого результата и без необходимости использовать карты на известность даже при их полном упразднении из игры. Т.е. упразднение карт даже подтолкнёт заинтересованных в политике игроков к мультоводству.

Надо менять всю систему! Переделать карты на известность мало!

**Comment by Tiendil** [comment]
Закрыто в пользу gh-2348
