### ISSUE TITLE
Эмиссары: Протекторат гильдии

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2377]
Реализовать логику объявление протектората гильдии над городом.

Было бы не плохо сделать галочку/кнопочку на эмисаре -- "Отказ от первого места в горорде", потому что в городе с несколькими эмисарами, и договоренностью о принадлежности города, устанешь считать цифирки, чтобы ненароком не нагадить союзнику.

Можно мерой менять протекторат. Эмик включает лидерскую меру на предъявление претензий на город. Мера работает 3 дня, по окончании протекторат меняется, если в процессе эмику не сбили лидерство.

В это случае можно отображать мероприятие в интерфейсе и создавать личные сообщения для заинтересованных игроков (руководящий состав гильдий с эмиссарами в городе).

**Comment by SilentWrangler** [comment]
Чисто напоминаю: сбили лидерство ИЛИ нанесли урон, в случае если в городе меньше четырёх эмиссаров и лидерство сохраняется при 0.
