### ISSUE TITLE
Забаненный на общение игрок может менять описание хранителя, историю героя

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2394]
Также проверить описание гильдии.

**Comment by Mefi13** [comment]
Забаненый на общение магистр гильдии передал через согильдийца, что нельзя менять описание гильдии: https://the-tale.org/forum/threads/713?page=425#m250320

В название задачи опечатка: профиль хранителя и история героя, вместо "хранителя, хранителя".

Просьба добавить для забаненых на общение игроков перечень ограничений для их аккаунтов, поскольку интуитивно бан-мут ожидается как ограничение общаться на форуме и ЛС, но на самом деле задевает куда больше механик. Также напомню, что у офицеров гильдии будет возможность работать с эмиссарами - стоит ли этот вид бана распространять на ограничения доступа и к этому функционалу?

**Comment by Mefi13** [comment]
А вообще, посидев в бан-муте я пришел к выводу, что всё же бан-мут лишь недоделка бана. Мне ничего не мешает создать твинков и писать с них. Уже так делали, когда получали мут на день за флейм, но игрокам было еще что сказать:
https://the-tale.org/forum/threads/8488?page=26#m249622
https://the-tale.org/forum/threads/8488?page=28#m249660
ПиратНику(вторая ссылка, удаленный пост) ткнули, что подобное наказывается и он почистил пост. Но это лишь пример того, что бан-мут не останавливает игроков, особенно, если они обижены (я не зову банить игроков выше + уже нет доказательной базы, кто чей твинк).
Далее, я все также могу передавать свои мысли через кого-то. В конце концов, учитывая, что я "обижен" администарцией, то я могу писать на гитхабе. 

Как я понимаю бан-мут. Это запрет на общение, т.е. запрет на функционал форума + отправку ЛС. При этом принять/отклонить гильдию должно быть можно. Это более милосердный вид бана, которой должен говорить игроку "остынь и возьми себя в руки", т.е. сама "игра" должна продолжаться. Его герой все также может влиять на игру и продолжать свое путешествие по Пандоре. Но, сейчас это не так. Книгу Судеб и голосование я еще понимаю в ограничениях, что их в наказание полезно добавить, но лингвистика и фольклор это лишь минус для Сказки. Да, у хранителя есть возможность издать после мута, но к тому времени у него может и желание потеряться. А если кто-то через эти механики решит обойти таки свой мут, то впаять уже ему бан, вместо бан-мута, и это правило "обойти наказание администрации" должно быть уточнено. Кроме лингвистики и фольклора считаю, что и профиль героя/хранителя не должен облагаться ограничениями. Игрок теряет доступ к общению, но историю своего Хранителя и героя относится к игре, к отыгрышу, а как я выше написал, я все-равно могу найти способы обойти мут, если захочу и я сильно "обижен". Поэтому мне кажется, что эта задача #2394 не нужна, и стоит рассмотреть вариант смягчения бан-мута.

И ещё стоит добавить в правилах уточнения на счет "обход наказания". Был прецедент, когда хранитель с перманентным баном создавал твинки и они были обнаружены с последующим повторным перманентом. Это правда не мешает хранителю создавать и далее твинки, которые не будут уже "попадаться". В тоже время мой твинк был забанен перманентно, хотя в то время аккаунт был в трехдневном муте. Как-то несоизмеримо, к тому же мейн аккаунт получил продление мута. Что мешает мне далее создавать твинков и писать от своего лица, если они получат перманент? Или что мешает кому-то писать от моего лица, когда я в муте?
