### ISSUE TITLE
Эмиссары: предупреждать о том, что не надо тратить всё влияние

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2421]
Добавить предупреждение при активации мероприятия с подробным объяснением причин и следствий.

**Comment by ArgoTheTale** [comment]
Желательно, чтобы это предупреждающее окно выскакивало только при первом запуске мероприятия эмиссару. Иначе оно будет сильно раздражать тех игроков, которые прекрасно понимают, что и зачем они делают.

**Comment by SilentWrangler** [comment]
Лучше сделать это галочкой в настройках гильдии. По умолчанию включена.
"Внимание, запуск мероприятия нанесёт урон эмиссару! Вы точно хотите продолжить? Это предупреждение можно отключить в настройках гильдии"
Что-то вроде такого.

**Comment by Tiendil** [comment]
Буду показывать предупреждение. когда начало мероприятия может оставить у эмиссара меньше 1000 влияния
