### ISSUE TITLE
Эмиссары: баланс стоимости мероприятий во влиянии

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2428]
На основе игровой статистики.

**Comment by SilentWrangler** [comment]
Тиендил. Цены во влиянии нормальные. Это старички просто на всякий случай первые квесты с тузами использовали) Новичков щас к чертям пришибёшь балансом)

**Comment by Tiendil** [comment]
При расчёте цены мероприятий во влиянии не учитывается параметр FIGHTERS_TO_EMISSARY, но в целом баланс наблюдает. 

Баланс станет лучше после gh-2488 (особенно, после пересмотра карт на влияние)
