### ISSUE TITLE
Карты Судьбы: увеличить размер кнопок «хранилище» и «превращение»

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2439]
Так как они используются значительно чаще кнопки «вы получаете карты доступные для»

Можно и как-нибудь рассположение поменять.

подробнее: https://the-tale.org/forum/threads/1539?page=151#m253044

**Comment by HuXTUS** [comment]
Можно вот так расположить. Из-за кнопки "вы получаете карты для" много места по горизонтали.

Так что эти две можно расположить горизонтально, а по вертикали дать больше воздуха.

![image](https://user-images.githubusercontent.com/6351438/71819471-d76de380-30ad-11ea-8da2-95ed66fe4909.png)
