### ISSUE TITLE
Новые иконки заданий

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2442]
Игрок moorka нарисовал:

![quests_icons_reworked_moo_style](https://user-images.githubusercontent.com/871672/71808874-e63da180-307f-11ea-89f2-5822b53dd0b4.png)

Необходимо внедрить в игру (либо заменить существующие, либо добавить альтернативный вариант).

Игроку начислить могущество.

**Comment by Tiendil** [comment]
Большинство мне нравится, они детализированнее предыдущих и вполне в стиле игры. Но есть несколько, которые, по-моему, потеряли свою семантику:

- Иконка с рукой — задание «потребовать должок». В оригинальной иконке рука в форме «указания», то есть якобы пальцем тычет в должника. В новой — рука бога с картины Микеланджело. Жест должен быть осуждающий, а не помогающий (в целом, допустима и другая аналогия, не обязательно руку рисовать).
- Иконка с «бандитом» — задание «шпионаж». В оригинальной иконке нарисован «шпион» в капюшоне, на новой скорее обычный бандит с большой дороге. Тоже потеря семантики.
- Иконка с деньгами — следующая трата героя. В целом устраивает, но что-то в ней не то, не пойму что :-) Может быть потому, что она лучше подошла бы для транжирства, а не для трат. Да, я понимаю, что у нас сейчас именно транжирство, но всё-таки надо задел на будущее делать.
- Иконка с воином на колене — посещение священного города. В оригинальной иконке был молящийся герой, в новой скорее викинг, рассказывающий о дальних походах, или рыцарь клянующися в верности своей даме :-)

**Comment by moorkamoorka** [comment]
Бросил в личку в дискорде скорректированный вариант.

**Comment by Tiendil** [comment]
[](url)
![2_](https://user-images.githubusercontent.com/871672/85644250-18c76f00-b69f-11ea-881a-151b7c85d3df.png)

**Comment by Tiendil** [comment]
@moorkamoorka Спасибо. Добавлю в следующем обновлении.
