### ISSUE TITLE
Вернуть ограничение на максимальное количество мастеров в городе

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2468]
Предполагалось, что отсутствие ограничения будет иногда использоватся для ролеплеея.
Фактически, стала активно использоваться для овероптимизации карты игры и нивелировала необходимость бороться за размер города. 
Большинство городов сейчас имеет количество Мастеров больше расчётного.

```
id 1 мастеров 6 (допустимый максимум 3) разница 3 размер 3 (необходимый размер 9)
id 3 мастеров 5 (допустимый максимум 3) разница 2 размер 3 (необходимый размер 7)
id 4 мастеров 6 (допустимый максимум 3) разница 3 размер 3 (необходимый размер 9)
id 5 мастеров 6 (допустимый максимум 3) разница 3 размер 4 (необходимый размер 9)
id 6 мастеров 6 (допустимый максимум 3) разница 3 размер 4 (необходимый размер 9)
id 7 мастеров 6 (допустимый максимум 4) разница 2 размер 5 (необходимый размер 9)
id 8 мастеров 5 (допустимый максимум 4) разница 1 размер 6 (необходимый размер 7)
id 10 мастеров 6 (допустимый максимум 4) разница 2 размер 5 (необходимый размер 9)
id 11 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 13 мастеров 6 (допустимый максимум 5) разница 1 размер 8 (необходимый размер 9)
id 14 мастеров 5 (допустимый максимум 3) разница 2 размер 3 (необходимый размер 7)
id 19 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 20 мастеров 6 (допустимый максимум 5) разница 1 размер 8 (необходимый размер 9)
id 21 мастеров 6 (допустимый максимум 5) разница 1 размер 8 (необходимый размер 9)
id 22 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 23 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 24 мастеров 6 (допустимый максимум 5) разница 1 размер 7 (необходимый размер 9)
id 25 мастеров 6 (допустимый максимум 3) разница 3 размер 4 (необходимый размер 9)
id 26 мастеров 5 (допустимый максимум 2) разница 3 размер 2 (необходимый размер 7)
id 28 мастеров 5 (допустимый максимум 3) разница 2 размер 4 (необходимый размер 7)
id 29 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 30 мастеров 6 (допустимый максимум 2) разница 4 размер 2 (необходимый размер 9)
id 32 мастеров 6 (допустимый максимум 3) разница 3 размер 4 (необходимый размер 9)
id 34 мастеров 4 (допустимый максимум 3) разница 1 размер 3 (необходимый размер 5)
id 39 мастеров 6 (допустимый максимум 3) разница 3 размер 4 (необходимый размер 9)
id 40 мастеров 5 (допустимый максимум 3) разница 2 размер 4 (необходимый размер 7)
id 42 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 45 мастеров 6 (допустимый максимум 4) разница 2 размер 6 (необходимый размер 9)
id 46 мастеров 4 (допустимый максимум 3) разница 1 размер 4 (необходимый размер 5)
id 47 мастеров 4 (допустимый максимум 3) разница 1 размер 4 (необходимый размер 5)
id 48 мастеров 4 (допустимый максимум 3) разница 1 размер 4 (необходимый размер 5)
id 50 мастеров 3 (допустимый максимум 2) разница 1 размер 1 (необходимый размер 3)
id 51 мастеров 4 (допустимый максимум 3) разница 1 размер 4 (необходимый размер 5)
```

Вернуть ограничение планируется в виде штрафа к стабильности.

**Comment by ArgoTheTale** [comment]
Перенеси реализацию на 0.4.1, потому что надо делать вместе с https://github.com/the-tale/the-tale/issues/2467. Иначе города колбасит по экономике и размеру, будут постоянные проблемы.

А ещё лучше сделай как раньше, когда ограничение на переселение работало только в момент переселения (нельзя переселить Мастера в город, если он недостаточно большой, но нет никаких штрафов, если размер города с тех пор упал). Раньше, во времена советников, так и было. И это было хорошо. Имела место кооперация и взаимопомощь, когда гильдии договаривались друг с другом, сначала нам прибавить советника, потом переселяемся и помогаем вам. В твоей нынешней реализации ни о какой кооперации не может быть и речи.

**Comment by Tiendil** [comment]
>А ещё лучше сделай как раньше

Раньше советники убивались, если им не было места в городе.

Я подумаю что можно сделать с #2467

**Comment by ArgoTheTale** [comment]
> Раньше советники убивались, если им не было места в городе.

Нет, Тииндил. Ты уже не помнишь, но было всё совсем по-другому. Советники убивались только если у них было меньше 5% влияния к концу часа (пересчёт влияния производился каждый час). И было время неуязвимости (пара недель вроде), чтобы нового советника успели поднять по влиянию больше этих 5%.

**Comment by Tiendil** [comment]
Это да, но большинство, вроде, всё-таки убивалось. Рано или поздно.

**Comment by ArgoTheTale** [comment]
Так зависимость-то была не от размера города, я о чём толкую! А крупные гильдии держали многих своих советников очень долго. Та же Орда, к примеру, очень трепетно относилась и к постройкам (были самые древние на карте до моих глобальных перестроек), и к советникам (большинство нынешних Мастеров с самыми маленькими порядковыми номерами — выходцы из Орды).
