### ISSUE TITLE
Задания: анализ эффект появления регионов и балансировка

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2472]
При реализации задачи gh-2470 пояилась возможность управлять регионом выполнения заданий героями.

Необходимо проанализировать их работу (есть риск собирания всех героев в один регион) и отбалансировать.

Возможные направления:

- вести подсчёт выполненых заданий для каждого города и для городов с небольшим количеством заданий давать бонус к опыту (и влиянию?)
- расчитывать количество опыта/влияния исходя из размера региона

**Comment by ArgoTheTale** [comment]
> При реализации задачи [gh-2470](https://github.com/the-tale/the-tale/issues/2470) пояилась возможность управлять регионом выполнения заданий героями.
> 
> Необходимо проанализировать их работу (есть риск собирания всех героев в один регион) и отбалансировать.
> 
> Возможные направления:
> 
> * вести подсчёт выполненых заданий для каждого города и для городов с небольшим количеством заданий давать бонус к опыту (и влиянию?)
> * расчитывать количество опыта/влияния исходя из размера региона

Можно сделать акцент на ближнем круге. Он ограничен по числе игроков, а значит другие будут вынуждены расселяться на незанятые территории.
