### ISSUE TITLE
Навигация: увеличить влияние пошлины на поиск пути героями

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2500]
Пошлина должна оказывать достаточно сильное влияние, чтобы герои обходили города с ней в большинстве случаев.

**Comment by ArgoTheTale** [comment]
Предлагаю сделать зависимость не просто от величины пошлины, а ещё и от текущей суммы золота у героя на кармане. Потерять 20% при тысяче монет в кармане не так страшно, как потерять 10% при пяти тысячах.

**Comment by Tiendil** [comment]
Закрыто в пользу gh-672
