### ISSUE TITLE
Удаление кнопки «помочь» и энергии

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2541]
Карты Судьбы, которые задумывались именно как замена помощи уже достаточно зрелый механизм. Нет смысла иметь две механики, занимающиеся одним и тем же.

Конечно, хотелось бы не удалять энергию + помощь, а заменить на что-нибудь другое (например, на молитвы героев), но время реализации такой замены непрогнозируемо.

Поэтому, чтобы не жить вечно с двумя однотипными механиками, я принял волевое решение удалить механику помощи.

**Comment by Htopik** [comment]
Компенсации за удаление огромных запасов энергии не будет? Опять же это очень сильно нерфит могущество, которое давало очень сильный баф к кнопке помощи, и окончательно выкидывает в мусорку всех спутников с особенностью "не жилец". Может тогда убрать эту особенность тоже?

**Comment by IoannSahin** [comment]
Помощь — явное воздействие на героя. Оно отражается в журнале игрока фразой, оно влияет на миролюбие героя. Ну и "помочь" — это единственная кнопка, на которую игрок может вволю потыкать, получив небольшое, но ЯВНО видимое влияние на героя. Карты, влияющие на героя, не находят никакого отклика в геройской жизни — они просто берут и подкручивают конкретный параметр. Не ощущаются, не погружают в мир игры. Без помощи И механик, её полноценно заменяющих, Сказка будет куда более пустой и неинтересной для новичков. 

Ах да, восстановление энергии Хранителям и редкое вмешательство Хранителей явной помощью прописано в лоре игры, в каноне. Так что...
