### ISSUE TITLE
Уточнить описание «бана на общения»

### ISSUE THREAD

**Issue by Tiendil** [the-tale/the-tale#2608]
На странице https://the-tale.org/guide/behavior-rules указано, про запрет общения на форуме, хотя вводится полный запрет любого общения (и косвенного, например, через книгу судеб).

Надо уточнить. 

Возможно, надо вынести ссылку на эти правила в главное меню.

**Comment by CaptainCollie** [comment]
А где главное меню?

**Comment by Tiendil** [comment]
В верху сайта: там где логотип, ссылки на чат, форум, etc.
